### ISSUE TITLE
Can Not load generators/cells/base Rails 4.2 

### ISSUE THREAD

**Issue by tbrooke** [apotonick/cells#261]
I get the following with the cells generator

users/tmb/brookesons/lawgix/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- generators/cells/base (LoadError)

**Comment by apotonick** [comment]
Hey Tom, may I enquire which Cells version you're using?

**Comment by tbrooke** [comment]
Gemfile:

gem 'cells', git: "https://github.com/apotonick/cells"

Version RB

module VERSION
    MAJOR = 4
    MINOR = 0
    TINY  = 0
    PRE   = 'alpha1'

**Comment by EppO** [comment]
I get the same issue when using Cells 4.0.beta2 and rspec-cells (either master branch or 0.2.2).
the cell controller and views are created but the specs file fails to generate.

**Comment by apotonick** [comment]
The rspec-cells version for Cells 4 is yet to be written - it will only be a few lines of code but someone's gotta do it! :wink:

**Comment by apotonick** [comment]
This is fixed in the new rspec-cells 0.3 release.

**Comment by vishakhasawant** [comment]
I am still getting this error with apotomo-1.3.1 and rails 4.2. I tried using master version of both apotomo and cells but that didnt work. Below is the stacktrace.
```ruby
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- generators/cells/base (LoadError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/apotomo-1.3.1/lib/generators/apotomo/widget_generator.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:334:in `block (2 levels) in lookup'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:330:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:330:in `block in lookup'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:329:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:329:in `lookup'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:138:in `find_by_namespace'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/generators.rb:155:in `invoke'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/workspace/apotomo_demo/bin/rails:8:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by apotonick** [comment]
Apotomo doesn't work with Cells 4, yet.

**Comment by dineshPallapa** [comment]
Is their any replacement or any supported methods for Apotomo to make work with cells 4.1.3

**Comment by apotonick** [comment]
Sorry @dineshPallapa, not really - I would love to support Cells with Apotomo but don't have the time for "experiments"... :cry:
